import type { User, Course, Activity } from "./types";

export const USERS: User[] = [
  {
    id: "u1",
    name: "María González",
    email: "estudiante@skillhub.com",
    password: "123456",
    role: "student",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&auto=format",
    joinDate: "2024-01-15",
    active: true,
  },
  {
    id: "u2",
    name: "Carlos Martínez",
    email: "profesor@skillhub.com",
    password: "123456",
    role: "teacher",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
    joinDate: "2023-08-20",
    active: true,
  },
  {
    id: "u3",
    name: "Laura Rodríguez",
    email: "admin@skillhub.com",
    password: "123456",
    role: "admin",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=80&h=80&fit=crop&auto=format",
    joinDate: "2023-01-05",
    active: true,
  },
];

export const COURSES: Course[] = [
  {
    id: "c1",
    title: "Introducción a Python",
    description: "Aprende los fundamentos de Python desde cero. Cubre variables, estructuras de control, funciones, y programación orientada a objetos.",
    category: "Programación",
    level: "Principiante",
    duration: "24 horas",
    rating: 4.9,
    students: 1240,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1526379879527-8559ecfcaec0?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-05-10",
    objectives: [
      "Comprender la sintaxis básica de Python",
      "Trabajar con variables y tipos de datos",
      "Implementar estructuras de control",
      "Crear funciones reutilizables",
      "Aplicar principios de POO",
    ],
    modules: [
      {
        id: "m1",
        title: "Introducción a Python",
        description: "Fundamentos del lenguaje",
        order: 1,
        contents: [
          { id: "co1", title: "¿Qué es Python?", type: "video", description: "Historia y usos de Python", order: 1, status: "published" },
          { id: "co2", title: "Instalación del entorno", type: "video", description: "Configurar Python y VS Code", order: 2, status: "published" },
          { id: "co3", title: "Tu primer programa", type: "text", description: "Hello World en Python", order: 3, status: "published" },
        ],
        activities: [
          { id: "a1", title: "Ejercicio: Primer script", description: "Crear tu primer programa en Python", instructions: "Escribe un programa que solicite tu nombre y lo salude.", maxScore: 100, deadline: "2025-07-15", status: "graded", score: 95, courseId: "c1", courseName: "Introducción a Python", moduleId: "m1", moduleName: "Introducción a Python" },
        ],
      },
      {
        id: "m2",
        title: "Variables y estructuras",
        description: "Tipos de datos y estructuras",
        order: 2,
        contents: [
          { id: "co4", title: "Variables y tipos de datos", type: "video", description: "int, float, str, bool", order: 1, status: "published" },
          { id: "co5", title: "Listas y tuplas", type: "video", description: "Colecciones en Python", order: 2, status: "published" },
          { id: "co6", title: "Diccionarios", type: "text", description: "Key-value pairs", order: 3, status: "published" },
        ],
        activities: [
          { id: "a2", title: "Ejercicio: Listas", description: "Manipulación de listas", instructions: "Crea una lista de 10 elementos y realiza operaciones básicas.", maxScore: 100, deadline: "2025-07-20", status: "submitted", courseId: "c1", courseName: "Introducción a Python", moduleId: "m2", moduleName: "Variables y estructuras" },
        ],
      },
      {
        id: "m3",
        title: "Funciones",
        description: "Definición y uso de funciones",
        order: 3,
        contents: [
          { id: "co7", title: "Definición de funciones", type: "video", description: "def, return, parámetros", order: 1, status: "published" },
          { id: "co8", title: "Funciones lambda", type: "video", description: "Funciones anónimas", order: 2, status: "published" },
        ],
        activities: [
          { id: "a3", title: "Ejercicio: Funciones", description: "Crear funciones útiles", instructions: "Implementa 5 funciones que resuelvan problemas matemáticos básicos.", maxScore: 100, deadline: "2025-07-25", status: "pending", courseId: "c1", courseName: "Introducción a Python", moduleId: "m3", moduleName: "Funciones" },
        ],
      },
      {
        id: "m4",
        title: "Programación Orientada a Objetos",
        description: "Clases y objetos en Python",
        order: 4,
        contents: [
          { id: "co9", title: "Clases y objetos", type: "video", description: "Fundamentos de POO", order: 1, status: "published" },
          { id: "co10", title: "Herencia y polimorfismo", type: "video", description: "Jerarquías de clases", order: 2, status: "published" },
        ],
        activities: [],
      },
    ],
  },
  {
    id: "c2",
    title: "Matemáticas para Programación",
    description: "Fundamentos matemáticos esenciales para todo programador: álgebra, estadística y matemáticas discretas.",
    category: "Matemáticas",
    level: "Intermedio",
    duration: "18 horas",
    rating: 4.7,
    students: 843,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-04-18",
    objectives: [
      "Álgebra lineal aplicada",
      "Estadística descriptiva",
      "Probabilidad básica",
      "Matemáticas discretas",
    ],
    modules: [
      {
        id: "m5",
        title: "Álgebra Lineal",
        description: "Vectores y matrices",
        order: 1,
        contents: [
          { id: "co11", title: "Vectores", type: "video", description: "Operaciones con vectores", order: 1, status: "published" },
          { id: "co12", title: "Matrices", type: "video", description: "Multiplicación de matrices", order: 2, status: "published" },
        ],
        activities: [],
      },
    ],
  },
  {
    id: "c3",
    title: "Fundamentos de Inteligencia Artificial",
    description: "Introducción a los conceptos clave de IA, machine learning, redes neuronales y aplicaciones prácticas.",
    category: "Inteligencia Artificial",
    level: "Intermedio",
    duration: "32 horas",
    rating: 4.8,
    students: 1567,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-06-01",
    objectives: [
      "Comprender conceptos fundamentales de IA",
      "Implementar modelos de ML básicos",
      "Trabajar con redes neuronales",
      "Aplicar IA en casos reales",
    ],
    modules: [
      {
        id: "m6",
        title: "Introducción a IA",
        description: "Conceptos básicos",
        order: 1,
        contents: [
          { id: "co13", title: "¿Qué es la IA?", type: "video", description: "Historia y aplicaciones", order: 1, status: "published" },
        ],
        activities: [],
      },
    ],
  },
  {
    id: "c4",
    title: "Desarrollo Web Moderno",
    description: "Domina HTML5, CSS3, JavaScript moderno, React y las mejores prácticas del desarrollo web actual.",
    category: "Desarrollo Web",
    level: "Principiante",
    duration: "40 horas",
    rating: 4.6,
    students: 2103,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-05-22",
    objectives: [
      "HTML5 semántico",
      "CSS3 y diseño responsive",
      "JavaScript ES6+",
      "React y componentes",
    ],
    modules: [
      {
        id: "m7",
        title: "HTML y CSS",
        description: "Fundamentos del frontend",
        order: 1,
        contents: [
          { id: "co14", title: "Estructura HTML", type: "video", description: "Tags y semántica", order: 1, status: "published" },
        ],
        activities: [],
      },
    ],
  },
  {
    id: "c5",
    title: "Bases de Datos SQL",
    description: "Aprende a diseñar, crear y gestionar bases de datos relacionales con SQL, desde lo básico hasta consultas avanzadas.",
    category: "Bases de Datos",
    level: "Principiante",
    duration: "20 horas",
    rating: 4.7,
    students: 921,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-03-14",
    objectives: [
      "Diseño de bases de datos",
      "Consultas SELECT avanzadas",
      "Joins y subconsultas",
      "Transacciones y optimización",
    ],
    modules: [],
  },
  {
    id: "c6",
    title: "Introducción a Ciencia de Datos",
    description: "Análisis de datos con Python, Pandas, NumPy y visualización con Matplotlib y Seaborn.",
    category: "Ciencia de Datos",
    level: "Intermedio",
    duration: "28 horas",
    rating: 4.5,
    students: 678,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-04-05",
    objectives: ["Pandas y NumPy", "Análisis exploratorio", "Visualización de datos"],
    modules: [],
  },
  {
    id: "c7",
    title: "Fundamentos de Ciberseguridad",
    description: "Principios esenciales de seguridad informática, protección de sistemas, criptografía y análisis de vulnerabilidades.",
    category: "Ciberseguridad",
    level: "Intermedio",
    duration: "22 horas",
    rating: 4.8,
    students: 534,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&h=220&fit=crop&auto=format",
    status: "draft",
    updatedAt: "2025-06-10",
    objectives: ["Seguridad en redes", "Criptografía básica", "Análisis de vulnerabilidades"],
    modules: [],
  },
  {
    id: "c8",
    title: "Programación Orientada a Objetos",
    description: "Principios de POO aplicados en Java: encapsulación, herencia, polimorfismo y patrones de diseño.",
    category: "Programación",
    level: "Avanzado",
    duration: "26 horas",
    rating: 4.6,
    students: 445,
    teacher: "Carlos Martínez",
    teacherId: "u2",
    image: "https://images.unsplash.com/photo-1564865878688-9a244444042a?w=400&h=220&fit=crop&auto=format",
    status: "published",
    updatedAt: "2025-02-28",
    objectives: ["Encapsulación", "Herencia", "Polimorfismo", "Patrones de diseño"],
    modules: [],
  },
];

export const STUDENT_ENROLLMENTS: { courseId: string; progress: number; lastContent: string; completed: boolean }[] = [
  { courseId: "c1", progress: 75, lastContent: "Listas y tuplas", completed: false },
  { courseId: "c4", progress: 45, lastContent: "Estructura HTML", completed: false },
  { courseId: "c3", progress: 20, lastContent: "¿Qué es la IA?", completed: false },
  { courseId: "c5", progress: 100, lastContent: "Transacciones", completed: true },
];

export const STUDENT_ACTIVITIES: Activity[] = [
  {
    id: "a1",
    title: "Ejercicio: Primer script",
    description: "Crear tu primer programa en Python",
    instructions: "Escribe un programa que solicite al usuario su nombre y edad, y muestre un mensaje de saludo personalizado con su información.",
    maxScore: 100,
    deadline: "2025-07-15",
    status: "graded",
    score: 95,
    courseId: "c1",
    courseName: "Introducción a Python",
    moduleId: "m1",
    moduleName: "Introducción a Python",
  },
  {
    id: "a2",
    title: "Ejercicio: Listas",
    description: "Manipulación de listas en Python",
    instructions: "Crea una lista de 10 elementos numéricos y realiza las siguientes operaciones: ordenar, buscar el máximo, el mínimo y calcular el promedio.",
    maxScore: 100,
    deadline: "2025-07-20",
    status: "submitted",
    courseId: "c1",
    courseName: "Introducción a Python",
    moduleId: "m2",
    moduleName: "Variables y estructuras",
  },
  {
    id: "a3",
    title: "Ejercicio: Funciones",
    description: "Crear funciones útiles en Python",
    instructions: "Implementa 5 funciones que resuelvan los siguientes problemas: factorial, fibonacci, número primo, palíndromo y conversión de temperatura.",
    maxScore: 100,
    deadline: "2025-07-25",
    status: "pending",
    courseId: "c1",
    courseName: "Introducción a Python",
    moduleId: "m3",
    moduleName: "Funciones",
  },
  {
    id: "a4",
    title: "Proyecto: Landing Page",
    description: "Crear una página web completa",
    instructions: "Diseña y desarrolla una landing page responsive usando HTML5 y CSS3. Debe incluir: header con navegación, sección hero, sección de características y footer.",
    maxScore: 100,
    deadline: "2025-08-01",
    status: "pending",
    courseId: "c4",
    courseName: "Desarrollo Web Moderno",
    moduleId: "m7",
    moduleName: "HTML y CSS",
  },
];

export const ADMIN_USERS = [
  { id: "u1", name: "María González", email: "estudiante@skillhub.com", role: "Estudiante", status: "active", joinDate: "2024-01-15", avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=40&h=40&fit=crop&auto=format" },
  { id: "u2", name: "Carlos Martínez", email: "profesor@skillhub.com", role: "Profesor", status: "active", joinDate: "2023-08-20", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&auto=format" },
  { id: "u3", name: "Laura Rodríguez", email: "admin@skillhub.com", role: "Administrador", status: "active", joinDate: "2023-01-05", avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&auto=format" },
  { id: "u4", name: "Ana López", email: "ana@example.com", role: "Estudiante", status: "active", joinDate: "2024-03-10", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&auto=format" },
  { id: "u5", name: "Pedro Ramírez", email: "pedro@example.com", role: "Estudiante", status: "active", joinDate: "2024-02-22", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&auto=format" },
  { id: "u6", name: "Sofía Herrera", email: "sofia@example.com", role: "Profesor", status: "active", joinDate: "2023-11-14", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&auto=format" },
  { id: "u7", name: "Miguel Torres", email: "miguel@example.com", role: "Estudiante", status: "inactive", joinDate: "2023-12-01", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=40&h=40&fit=crop&auto=format" },
  { id: "u8", name: "Valentina Cruz", email: "valentina@example.com", role: "Estudiante", status: "active", joinDate: "2024-04-05", avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=40&h=40&fit=crop&auto=format" },
  { id: "u9", name: "Andrés Morales", email: "andres@example.com", role: "Profesor", status: "active", joinDate: "2023-09-30", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=40&h=40&fit=crop&auto=format" },
  { id: "u10", name: "Camila Vargas", email: "camila@example.com", role: "Estudiante", status: "active", joinDate: "2024-05-18", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=40&h=40&fit=crop&auto=format" },
];

export const TEACHER_STUDENTS = [
  { id: "s1", name: "María González", avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=40&h=40&fit=crop&auto=format", course: "Introducción a Python", progress: 75, activities: "2/3", average: 4.5, status: "active" },
  { id: "s2", name: "Ana López", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&auto=format", course: "Desarrollo Web Moderno", progress: 60, activities: "5/8", average: 4.2, status: "active" },
  { id: "s3", name: "Pedro Ramírez", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=40&h=40&fit=crop&auto=format", course: "Bases de Datos SQL", progress: 100, activities: "8/8", average: 4.9, status: "active" },
  { id: "s4", name: "Miguel Torres", avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=40&h=40&fit=crop&auto=format", course: "Introducción a Python", progress: 30, activities: "1/3", average: 3.8, status: "inactive" },
  { id: "s5", name: "Valentina Cruz", avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=40&h=40&fit=crop&auto=format", course: "Fundamentos de IA", progress: 55, activities: "4/6", average: 4.6, status: "active" },
  { id: "s6", name: "Andrés Morales", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=40&h=40&fit=crop&auto=format", course: "Matemáticas para Programación", progress: 85, activities: "7/8", average: 4.4, status: "active" },
];

export const CATEGORIES = [
  { id: "cat1", name: "Programación", courses: 18, color: "#3157D5", active: true },
  { id: "cat2", name: "Matemáticas", courses: 9, color: "#18B6A4", active: true },
  { id: "cat3", name: "Inteligencia Artificial", courses: 12, color: "#7C5CFC", active: true },
  { id: "cat4", name: "Ciencia de Datos", courses: 11, color: "#3157D5", active: true },
  { id: "cat5", name: "Ciberseguridad", courses: 7, color: "#EF4444", active: true },
  { id: "cat6", name: "Diseño", courses: 8, color: "#F59E0B", active: true },
  { id: "cat7", name: "Bases de Datos", courses: 6, color: "#18B6A4", active: true },
  { id: "cat8", name: "Desarrollo Web", courses: 15, color: "#10B981", active: false },
];

export const GROWTH_DATA = [
  { month: "Jun", usuarios: 850 },
  { month: "Jul", usuarios: 920 },
  { month: "Ago", usuarios: 980 },
  { month: "Sep", usuarios: 1020 },
  { month: "Oct", usuarios: 1050 },
  { month: "Nov", usuarios: 1080 },
  { month: "Dic", usuarios: 1100 },
  { month: "Ene", usuarios: 1130 },
  { month: "Feb", usuarios: 1170 },
  { month: "Mar", usuarios: 1200 },
  { month: "Abr", usuarios: 1230 },
  { month: "May", usuarios: 1248 },
];

export const ENROLLMENT_DATA = [
  { month: "Jun", inscripciones: 280 },
  { month: "Jul", inscripciones: 310 },
  { month: "Ago", inscripciones: 350 },
  { month: "Sep", inscripciones: 420 },
  { month: "Oct", inscripciones: 380 },
  { month: "Nov", inscripciones: 430 },
  { month: "Dic", inscripciones: 390 },
  { month: "Ene", inscripciones: 460 },
  { month: "Feb", inscripciones: 510 },
  { month: "Mar", inscripciones: 490 },
  { month: "Abr", inscripciones: 540 },
  { month: "May", inscripciones: 475 },
];

export const COURSES_BY_CATEGORY = [
  { name: "Programación", cursos: 18 },
  { name: "Web", cursos: 15 },
  { name: "IA", cursos: 12 },
  { name: "Datos", cursos: 11 },
  { name: "Matemáticas", cursos: 9 },
  { name: "Diseño", cursos: 8 },
  { name: "Seguridad", cursos: 7 },
  { name: "BD", cursos: 6 },
];

export const USER_DISTRIBUTION = [
  { name: "Estudiantes", value: 1050, color: "#3157D5" },
  { name: "Profesores", value: 180, color: "#18B6A4" },
  { name: "Administradores", value: 18, color: "#7C5CFC" },
];

export const WEEKLY_PROGRESS = [
  { day: "Lun", horas: 1.5 },
  { day: "Mar", horas: 2 },
  { day: "Mié", horas: 0.5 },
  { day: "Jue", horas: 3 },
  { day: "Vie", horas: 2.5 },
  { day: "Sáb", horas: 1 },
  { day: "Dom", horas: 0 },
];

export const TEACHER_MONTHLY = [
  { month: "Ene", estudiantes: 80 },
  { month: "Feb", estudiantes: 92 },
  { month: "Mar", estudiantes: 98 },
  { month: "Abr", estudiantes: 105 },
  { month: "May", estudiantes: 112 },
  { month: "Jun", estudiantes: 128 },
];

export const POPULAR_COURSES = [
  { name: "Introducción a Python", students: 1240, rating: 4.9 },
  { name: "Matemáticas para Programación", students: 843, rating: 4.7 },
  { name: "Fundamentos de IA", students: 1567, rating: 4.8 },
  { name: "Desarrollo Web Moderno", students: 2103, rating: 4.6 },
  { name: "Bases de Datos SQL", students: 921, rating: 4.7 },
];
